apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-developer
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/cgradwohl/flux_developer
  ref:
    branch: main
---
# this CRD defines a gitops pipeline for dev env
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization

metadata:
  name: configmaps
  namespace: flux-system

spec:
  interval: 1m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-developer
  path: ./environments/dev
