apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Git sources
  - ./gitrepository-platform.yaml
  - ./gitrepository-developer.yaml

  # Flux piplines
  - ./kustomization-configmaps.yaml

  # Platform infrastructure
  - ../../infrastructure/csi-secrets-store/dev
