apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../runtime

namePrefix: beetle-

commonLabels:
  app.kubernetes.io/name: beetle
  app.kubernetes.io/part-of: platform

images:
  - name: app
    newName: beetle
    newTag: latest
