apiVersion: apps/v1
kind: Deployment
metadata:
  name: beetle-app
  namespace: default
  labels:
    app: beetle-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beetle-app
  template:
    metadata:
      labels:
        app: beetle-app
    spec:
      containers:
        - name: beetle-app
          image: beetle-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /etc/beetle-config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: beetle-config
