apiVersion: v1
kind: Service
metadata:
  name: beetle-app
  namespace: default
spec:
  selector:
    app: beetle-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
