apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prd-configmaps
  namespace: flux-system
spec:
  interval: 1m
  prune: true
  wait: true

  sourceRef:
    kind: GitRepository
    name: flux-developer
  path: ./environments/prd
