apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: beetle-dev-config
  namespace: flux-system
spec:
  interval: 1m
  prune: true
  wait: true

  sourceRef:
    kind: GitRepository
    name: flux-developer

  # points to the dev folder in the developer repo aka the folder containing
  # kustomization.yaml
  path: ./beetle/dev

  postBuild:
    substitute:
      SERVICE_NAME: beetle
      ENV: dev
